stages:
  prepare:
    cmd: PYTHONPATH=. python3 credit_fraud_pipeline/scripts/prepare.py
    deps:
    - credit_fraud_pipeline/scripts/prepare.py
    - data/archive.zip
    params:
    - prepare.data_path
    outs:
    - data/prepared.pkl
  feature_engenc:
    cmd: PYTHONPATH=. python3 credit_fraud_pipeline/scripts/feature_engenc.py
    deps:
    - credit_fraud_pipeline/scripts/feature_engenc.py
    - data/prepared.pkl
    params:
    - feature_engenc.encoder_path
    outs:
    - data/features.pkl
    - data/labels.pkl
    - pickles/encoder.pkl
  train:
    cmd: PYTHONPATH=. python3 credit_fraud_pipeline/scripts/train.py
    deps:
    - credit_fraud_pipeline/scripts/train.py
    - data/features.pkl
    - data/labels.pkl
    params:
    - train.test_size
    - train.n_iter
    - train.init_points
    - train.cv
    - train.stratified
    - train.shuffle
    - train.balanced
    - train.num_boost_round
    outs:
    - pickles/model.pkl
    metrics:
    - pickles/metrics.json:
        cache: false
