prepare:
  data_path: 'data/creditcard.csv'
  archive_path: 'data/archive.zip'
feature_engenc:
  encoder_path: 'models/encoder.pkl'
train:
  test_size: 0.2
  n_iter: 10
  init_points: 3
  cv: 5
  stratified: True
  shuffle: True
  balanced: False
  num_boost_round: 100
