prepare:
  data_path: 'data/creditcard.csv'
  archive_path: 'data/archive.zip'
feature_engenc:
  encoder_path: 'pickles/encoder.pkl'
train:
  test_size: 0.3
  val_size: 0.3
  n_iter: 20
  init_points: 4
  cv: 3
  stratified: True
  shuffle: True
  balanced: False
  num_boost_round: 300
  scale_pos_weight: 300
